name: ci

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
    steps:
      - { uses: actions/checkout@v3, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v3, with: { node-version: 18, cache: 'yarn' } }
      - { name: yarn, run: yarn --frozen-lockfile }

      - name: build
        run: yarn build-prod

      - name: test
        run: |
          yarn test
          yarn smoke-test
